import type { AppData } from '../types';

export const PASSWORD = 'tropic.boost';

export const seedData: AppData = {
  events: [
    {
      id: 'evt-hyrox-mad',
      name: 'Hyrox Madrid',
      date: '2026-08-08',
      endDate: '2026-08-09',
      place: 'IFEMA, Madrid',
      cost: 850,
      createdAt: new Date().toISOString(),
      materialsUsed: [],
    },
    {
      id: 'evt-crossfit-bcn',
      name: 'CrossFit Open Barcelona',
      date: '2026-08-15',
      endDate: '2026-08-15',
      place: 'Parc del Fòrum, Barcelona',
      cost: 720,
      createdAt: new Date().toISOString(),
      materialsUsed: [],
    },
    {
      id: 'evt-trail-val',
      name: 'Valencia Running Trail',
      date: '2026-09-03',
      endDate: '2026-09-05',
      place: 'Ciudad de las Artes, Valencia',
      cost: 480,
      createdAt: new Date().toISOString(),
      materialsUsed: [],
    },
  ],
  products: [
    {
      id: 'prod-lotus',
      name: 'Lotus Boost',
      description:
        'Açaí con plátano, arándanos, galleta Lotus y mango. Dulce, crujiente y muy apetecible.',
      ingredients: ['Açaí', 'Plátano', 'Arándanos', 'Lotus', 'Mango'],
      price: 7.5,
      kcal: 360,
      tag: 'Sweet boost',
    },
    {
      id: 'prod-pb',
      name: 'PB Crunch',
      description:
        'Plátano, fresa, muesli y peanut butter sobre açaí. Recuperación con sabor y textura.',
      ingredients: ['Açaí', 'Plátano', 'Fresa', 'Muesli', 'Peanut butter'],
      price: 7.9,
      kcal: 390,
      tag: 'Recovery',
    },
    {
      id: 'prod-berry',
      name: 'Berry Power',
      description:
        'Fresa, arándanos, mango, muesli y peanut butter. Antioxidantes y energía post esfuerzo.',
      ingredients: [
        'Açaí',
        'Fresa',
        'Arándanos',
        'Mango',
        'Muesli',
        'Peanut butter',
      ],
      price: 8.2,
      kcal: 410,
      tag: 'Post workout',
    },
    {
      id: 'prod-passion',
      name: 'Passion Glow',
      description:
        'Kiwi, coco, maracuyá y miel. Toque tropical fresco para cargar energía en carrera.',
      ingredients: ['Açaí', 'Kiwi', 'Coco', 'Maracuyá', 'Miel'],
      price: 7.2,
      kcal: 340,
      tag: 'Pre / mid',
    },
  ],
  materials: [
    { id: 'mat-acai', name: 'Açaí base', price: 4.2, unit: 'kg' },
    { id: 'mat-platano', name: 'Plátano', price: 1.8, unit: 'kg' },
    { id: 'mat-fresa', name: 'Fresa', price: 3.5, unit: 'kg' },
    { id: 'mat-arandanos', name: 'Arándanos', price: 6.5, unit: 'kg' },
    { id: 'mat-mango', name: 'Mango', price: 2.9, unit: 'kg' },
    { id: 'mat-muesli', name: 'Muesli', price: 3.2, unit: 'kg' },
    { id: 'mat-pb', name: 'Peanut butter', price: 5.5, unit: 'kg' },
    { id: 'mat-lotus', name: 'Galleta Lotus', price: 4.8, unit: 'kg' },
    { id: 'mat-kiwi', name: 'Kiwi', price: 3.1, unit: 'kg' },
    { id: 'mat-coco', name: 'Coco rallado', price: 4.0, unit: 'kg' },
    { id: 'mat-maracuya', name: 'Maracuyá', price: 5.2, unit: 'kg' },
    { id: 'mat-miel', name: 'Miel', price: 6.0, unit: 'kg' },
  ],
  promotions: [
    {
      id: 'promo-10',
      name: '10% descuento',
      type: 'percent',
      value: 10,
      description: '10% sobre el total',
    },
    {
      id: 'promo-2e',
      name: '2 € de descuento',
      type: 'fixed',
      value: 2,
      description: 'Descuento fijo de 2 €',
    },
    {
      id: 'promo-50',
      name: 'Segundo bowl al 50%',
      type: 'second_half',
      value: 50,
      description: 'El bowl más barato al 50%',
    },
    {
      id: 'promo-staff',
      name: 'Staff',
      type: 'percent',
      value: 20,
      description: 'Descuento equipo / staff',
    },
    {
      id: 'promo-sponsor',
      name: 'Patrocinador',
      type: 'percent',
      value: 15,
      description: 'Descuento patrocinadores',
    },
  ],
  orders: [],
  orderCounter: {},
};
